# Generated by Django 3.2.8 on 2022-02-22 12:34

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('COM', 'Comedy'), ('DRA', 'Drama'), ('FAN', 'Fantasy'), ('HIS', 'Historical'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('SCI', 'Science Fiction'), ('THR', 'Thriller'), ('WES', 'Western'), ('OTH', 'Other')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('imdb_url', models.URLField(null=True, verbose_name='imdb')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField()),
                ('cover', models.ImageField(upload_to='img')),
                ('description', models.TextField(blank=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.genre')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
