# Generated by Django 3.2.8 on 2022-02-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='video.Genre'),
        ),
    ]
