# Generated by Django 3.2.8 on 2022-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220222_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, to='video.Genre'),
        ),
    ]
