# Generated by Django 3.2.8 on 2022-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 10.0)), name='Video_rating_range'),
        ),
    ]
